name = "art25"

compatibility_date = "2025-06-24"

[vars]
URL = "https://williamwhitaker.art"
NAME = "William Whitaker"
EMAIL = "william@williamwhitaker.art"
MASTO = "@commendable@mastodon.social"
DEV_SITE = "https://williamwhitaker.dev"

[assets]
directory = "./dist"